"""Consulta SQL de las lecturas actuales de gestión."""

CONSULTA_PERDIDA_LATENCIA_ACTUAL = """
SELECT
    IP,
    EQUIPO,
    PACKET_LOSS,
    LATENCIA_AVG,
    JITTER
FROM tiempos_red
WHERE RED = 'GESTION'
  AND (
      COALESCE(PACKET_LOSS, 0) > 10
      OR COALESCE(LATENCIA_AVG, 0) > 50
  )
ORDER BY
    PACKET_LOSS DESC,
    LATENCIA_AVG DESC,
    EQUIPO
"""
